# OpenTelemetry Collector Configuration
# This configuration receives traces and exports them to Jaeger

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    
  # Add resource attributes
  resource:
    attributes:
      - key: service.instance.id
        from_attribute: host.name
        action: insert
      - key: deployment.environment
        value: development
        action: upsert
        
  # Memory limiter prevents OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

exporters:
  # Export to Jaeger
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
      
  # Export to Prometheus (for metrics)
  prometheus:
    endpoint: "0.0.0.0:8889"
    
  # Debug exporter (logs to stdout)
  logging:
    loglevel: debug

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [jaeger, logging]
      
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]