# Prometheus configuration for collecting metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        
  # Scrape exported application metrics
  - job_name: 'otel-collector-prometheus-exporter'
    static_configs:
      - targets: ['otel-collector:8889']
        
  # Scrape Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']