server:
  port: "8080"
  address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  shutdown_timeout: 10s
  gzip: true
  cors: true
  recovery: true

logger:
  level: "info"
  encoding: "json"
  output_paths:
    - "stdout"
  error_output_paths:
    - "stderr"

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  max_message_size: 524288  # 512KB
  pong_wait: 60s
  ping_period: 54s

jwt:
  secret_key: "your-secret-key-change-in-production"
  access_token_ttl: 1h
  refresh_token_ttl: 168h  # 7 days
  issuer: "stmp-server"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "stmp_user"
  password: "stmp_password"
  database: "stmp_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m